model_id: Qwen/Qwen2.5-VL-7B-Instruct
model_family: qwen2.5-vl

LoRA:
  r: 64
  alpha: 128
  dropout: 0.05

loss_type: grad_ascent
tune_vision_tower: False
tune_mm_projector: True
tune_language_model: True
data_path: ./workspace/data/vpd_mix470k_ins-it379k_drivelm91k.json
split: retain
batch_size: 1
gradient_accumulation_steps: 16
max_grad_norm: 1.0
num_epochs: 3
save_dir: models/final_ft_${num_epochs}_epochs_lr${lr}_${model_family}_${split}
save_steps: 1800
lr: 5e-5
weight_decay: 0.01
seed: 233
workers: 4
lr_scheduler_type: "cosine"
warmup_ratio: 0.00
max_train_steps: -1
report_to: "wandb"
resume_from_checkpoint: ""
